name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23', '1.24', '1.25']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Start SFTP container (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          docker compose -f docker-sftp/docker-compose.yml up -d
          sleep 10  # Wait for container to be ready

      - name: Run tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic

      - name: Run tests (Windows - no SFTP)
        if: runner.os == 'Windows'
        run: |
          go test ./... -v -short
        shell: powershell

      - name: Upload coverage
        if: runner.os == 'Linux' && matrix.go-version == '1.25'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

      - name: Stop SFTP container (Linux/macOS)
        if: always() && runner.os != 'Windows'
        run: |
          docker compose -f docker-sftp/docker-compose.yml down